'frontpage_score_start' => 0.5,
'favourites_modifier' => 1,
'show_navigation_pseudo_leaves' => false,
'frontpage_limit_days' => 100,
'news_favourites_url' => '/favourites',
'show_navigation_pseudo_leaves' => false,
'delicious_enable' => true,
'delicious_modifier' => 1,
